### ISSUE TITLE
This is an interesting repo!

### ISSUE THREAD

**Issue by Jordy-VL** [jofas/invoice_generator#1]
Do you perhaps have an example of such a json file? 

I tried crafting one hastily, but did not get it to work. 

Thanks!

**Comment by jofas** [comment]
Hi @Jordy-VL,

thanks for your issue. I've updated the repo with an `examples/` directory and a `README` section that describes the dependencies you need and the command for actually creating the invoice as a pdf file. Hopefully this will help you. I'm a freelancing software developer, so the implemented scope is rather small (my invoices are legally not required to contain more information than I've implemented so far). Feel free to make feature requests if you want to use this package.
